### PR TITLE
service-builder master | change messaging on service consumption | LRDOCS-8120

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-8120

### CODE REVIEW

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
ci:forward

**Comment by rbohl** [comment]
ci:test:relevant

**Comment by jhinkey** [comment]
Looks good. Thanks, @rbohl !

**Comment by rbohl** [comment]
@jhinkey any tips on getting it past the CI bots? :sweat_smile: 

Should I be committing my run of Service Builder? I did here https://github.com/rbohl/liferay-portal/pull/30/commits/f4ab1b134430b499d23a39c8890fed43efa81093

**Comment by jhinkey** [comment]
I'm not familiar with satisfying the CI bots. I do know that you should run javadoc formatter (see Javadoc guidelines in readme folder) and source formatter too.

**Comment by rbohl** [comment]
Thanks; source formatter is happy, and I assume that the service buolder task generates good javadoc, but i'll try to run the formatJavadoc task and see if it helps.

I might just have to keep re-running the tests, or ask a friendly QA professional.

**Comment by rbohl** [comment]
ci:test:relevant

**Comment by rbohl** [comment]
ci:test:relevant

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
ci:test:sb

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
ci:retest

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
ci:relevant

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
ci:test:stop

**Comment by rbohl** [comment]
ci:close

**Pull request closed without merging**
