### PR TITLE
usm 7.3 | update sb template about service impl inspection | LPS-115531

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-115531

### CODE REVIEW

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
@drewbrokk, @jhinkey, I'd like to get feedback from you guys on this update to the SB template defined in `service_base_impl.ftl`.

**Comment by jhinkey** [comment]
I'm looking at it now, @rbohl . Thanks.

**Comment by jhinkey** [comment]
@rbohl - I think it would be good to elaborate on reasons for using the Impl method(s). Here's something that came to mind...

`Before using this method, consider using an equivalent method in the ${entity.humanName}LocalServiceImpl. If such methods exist, they are typically more robust and use parameters that fine-tune the operation and provide context.`

Also, make sure to put the starting `p` tag on its own line.

Hope that helps.

**Comment by jhinkey** [comment]
Here's another way of saying it ...

`Note: Calling an equivalent method in the ${entity.humanName}LocalServiceImpl is preferred over calling this method because such a method, if it exists, are more robust and use parameters that provide context and fine-tune the operation.`

**Comment by rbohl** [comment]
How about this?

> Important: Inspect the ${entity.humanName}LocalServiceImpl for overloaded versions of the method. If provided, use these   entry points to the API, as the implementation logic may require the additional parameters defined there.

**Comment by jhinkey** [comment]
I like it, @rbohl !

**Comment by rbohl** [comment]
ci: test:sf

**Comment by rbohl** [comment]
@jhinkey after my last commit I'm ready to send this one in. Is it expected that I would run Service Builder to propagate the changes to the template and commit the result here?

**Comment by rbohl** [comment]
ci:test:sf

**Comment by jhinkey** [comment]
@rbohl - Yes, I think building portal's services expected as a final commit.

**Comment by brianchandotcom** [comment]
@jhinkey @rbohl 4025655a7b2b32e1cadffd7f3f4b031e162fbf03 and bcebe55bc40227b25ea19b4bd4e92039a7a4ac11 

Type: git grep "Important:"

I merged this into my origin.

**Comment by rbohl** [comment]
Thanks @brianchandotcom 
When I was looking into using _Important:_ I found a couple of unrelated instances where it was written without the <strong> tags. I'm going to change these for consistency and send in a separate PR.

**Comment by brianchandotcom** [comment]
Thx @rbohl

**Pull request closed without merging**
