### PR TITLE
usm 7.3 | clarify role api usage | LPS-115531

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-115531

### CODE REVIEW

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
@drewbrokke can you look at this PR for accuracy before I send it up?

**Comment by drewbrokke** [comment]
Hmm, in this case the delete methods are equal, so I could "recommend" either one, in which case I don't see much benefit in recommending them.

**Comment by rbohl** [comment]
> Hmm, in this case the delete methods are equal, so I could "recommend" either one, in which case I don't see much benefit in recommending them.

Ahh right, good point. So we don't need any message for the `delete` methods. Everything else okay?

**Comment by drewbrokke** [comment]
Yup, the other parts look good. Thanks Russ!

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
ci:forward

**Pull request closed without merging**
