### PR TITLE
LRQA-51488 (revert one) | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-51488

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
`relevant` results about match that of head, a [flaky failure](https://testray.liferay.com/home/-/testray/cases/438911564) is showing up as unique

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
