### PR TITLE
javadoc 7.3 | for consistency important should be strong | LPS-115531

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-115531

### CODE REVIEW

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
@jhinkey, sorry to keep bugging you about this, I wanted to ensure consistency with Brian's rpeference to wrap the "Important:" string in `<strong>` tags. 

I found three places to update:
- `javadocs-all.xml` in portal-impl
- `DiscardWithCancelPolicy` in portal-impl
- `DiscardWithCancelPolicy` in portal-kernel

It looks as if the Javadoc for those classes is generated by javadocs-all.xml but I don't really know how this works. Should this change be made manually in all three locations or only the XML file?

**Comment by jhinkey** [comment]
@rbohl - javadocs-all.xml is generated based on the Javadoc in the .java files. So, if you would, just update the Discard* classes. Thanks!

**Comment by jhinkey** [comment]
... javadocs-all.xml is used in an online directory for our JSON web services.

**Comment by rbohl** [comment]
Ahh so I had it exactly backwards. Thanks Jim!

**Comment by rbohl** [comment]
ci:forward

**Pull request closed without merging**
