### PR TITLE
LRDOCS-9702 Change view.jsp to work with react component

### PR DESCRIPTION
**Pull request by ramonmsp**

### CODE REVIEW

**Comment by rbohl** [comment]
@ramonmsp I rebased on master and tried to deploy:

The -web project failed:
```
> Task :apps:liferay-f2m9.zip:f2m9-web:generateJSPJava FAILED
Compiling JSP files of project ':apps:liferay-f2m9.zip:f2m9-web' with /home/russell/liferay-bundles/master-dxp_12142021/tomcat-9.0.53/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:liferay-f2m9.zip:f2m9-web:generateJSPJava'.
> file:/home/russell/git/liferay-portal-worktrees/liferay-portal/modules/apps/liferay-f2m9.zip/f2m9-web/classes/META-INF/resources/view.jsp(6,57) PWC6188: The absolute uri: http://liferay.com/tld/react cannot be resolved in either web.xml or the jar files deployed with this application

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
20 actionable tasks: 5 executed, 15 up-to-date
```

**Comment by ramonmsp** [comment]
@rbohl I'll check it and return soon

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
@rbohl I pushed some updates at build.gradle and gw generateJSPJava works now!
Let me know if you find another problem :D

**Comment by rbohl** [comment]
Thanks @ramonmsp . It deploys successfully. Can you confirm if this is how it's supposed to look?

track-workflow

**Comment by rbohl** [comment]
@ramonmsp I rebuilt and deployed to today master, and it looks the same as in my screenshot above.

**Comment by ramonmsp** [comment]
@rbohl was looking at this and it is a CSS bug. Maybe another bug fix changed it. I'll make some changes and let you know when it's done

**Comment by ramonmsp** [comment]
@rbohl could you try again?

**Comment by rbohl** [comment]
Ok, this looks good:
track-workflow

Thanks Ramon!

**Comment by rbohl** [comment]
Hey @ramonmsp this is working, I just have one question for now: should the third party application need to add custom CSS for this to work?

**Comment by rbohl** [comment]
Last message until after the weekend, I promise :sweat_smile: 

I'm also having trouble building the project when I try to apply it to a workspace outside of `liferay-portal` (in `liferay-learn`). 
<details><summary>Click here for log:</summary>
$ ./gradlew deploy

> Task :f2m9-web:buildCSS
Using native Sass compiler
There are no files to compile

> Task :yarnInstall
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.05s.

> Task :f2m9-web:packageRunBuild FAILED
yarn run v1.13.0
$ liferay-npm-scripts build
/bin/sh: line 1: liferay-npm-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':f2m9-web:packageRunBuild'.
> Process 'command '/home/russell/git/liferay-learn/docs/dxp/latest/en/process-automation/workflow/developer-guide/creating-a-workflow-instance-tracker/resources/liferay-f2m9.zip/build/node/bin/node'' finished with non-zero exit value 1
</details>

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
@rbohl sorry for the delay, i was working on it.

**I just have one question for now: should the third party application need to add custom CSS for this to work?**

If the component is shown inside a modal, it is necessary to set the height and width properties. I removed some responsiveness properties to make the CSS simpler.

**I'm also having trouble building the project when I try to apply it to a workspace outside of liferay-portal (in liferay-learn).**

So, _liferay-npm-scripts build_ is necessary to build any JS code, and we can't run it inside a liferay-learn. We have to think in a solution for it. I thought that we put F2M9 on liferay-portal because of it

**Comment by ramonmsp** [comment]
@rbohl Do you have any examples of another team that we can follow?

**Comment by rafaprax** [comment]
Hey @ramonmsp,

I think that putting the F2M9 into liferay-portal is not an alternative. We tried to build this due to some restrictions we had at that moment, they were:

1. The instance was not available in the liferay official images.
2. To get a functional piece of code working as soon as possible that would be helpful to some stories about "make the instance tracker available to other parts of portal".

So, maybe we can reach the frontend infra team to know if there is an official solution for this case. What do you think?

Thx

**Comment by rbohl** [comment]
Hi @ramonmsp, I just ran into a build error: 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/russell/git/liferay-portal-worktrees/liferay-portal/modules/apps/liferay-f2m9.zip/f2m9-web/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':f2m9-web'.
> Project with path ':apps:frontend-taglib:frontend-taglib-react' could not be found in project ':f2m9-web'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by rbohl** [comment]
This has been deprioritized

**Pull request closed without merging**
