### PR TITLE
LRDOCS-7735 | Update supported ES 7 range in app.bnd

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7735
cc @lipusz

### CODE REVIEW

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
ci:forward

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
ci:forward

**Comment by pyoo47** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by rbohl** [comment]
ci:forward

**Comment by rbohl** [comment]
ci:forward

**Comment by rbohl** [comment]
ci:stop

**Pull request closed without merging**
