### PR TITLE
LPS-72098 Add javadoc to StringQuery

### PR DESCRIPTION
**Pull request by lipusz**
Related to arboliveira#254.

Thanks,
Tibor

### CODE REVIEW

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
@lipusz @arboliveira,
https://github.com/rbohl/liferay-portal/commit/37c41277f6fa9da74b087b412716f224438b961e

Please review my edit. I am not totally confident in my understanding, especially of the *Note*.

**Comment by lipusz** [comment]
Looks good to me. @rbohl

**Comment by rbohl** [comment]
Merged: https://github.com/brianchandotcom/liferay-portal/pull/48998

**Pull request closed without merging**
